version: '3.4'

services:
  syscoin:
    image: 'syscoin-dev'
    build:
      context: .
    restart: always
    ports:
      - '8369:8369'
      - '30303:30303'
    volumes:
      - ./syscoin:/syscoin/.syscoin
